//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndianaPark.PercorsiAvventura.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndianaPark.PercorsiAvventura.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorsi Avventura.
        /// </summary>
        internal static string AttrazioneDisplayedName {
            get {
                return ResourceManager.GetString("AttrazioneDisplayedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai selezionato nessun briefing in cui inserire il cliente.
        /// </summary>
        internal static string BriefingNonSelezionatoText {
            get {
                return ResourceManager.GetString("BriefingNonSelezionatoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefing non selezionato.
        /// </summary>
        internal static string BriefingNonSelezionatoTitle {
            get {
                return ResourceManager.GetString("BriefingNonSelezionatoTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli briefing per
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string ChooseBriefingFor {
            get {
                return ResourceManager.GetString("ChooseBriefingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo cliente è gia stato fatto uscire!.
        /// </summary>
        internal static string ClienteAlreadyExitedText {
            get {
                return ResourceManager.GetString("ClienteAlreadyExitedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string ClienteAlreadyExitedTitle {
            get {
                return ResourceManager.GetString("ClienteAlreadyExitedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi veramente far uscire {0} clienti dai percorsi?.
        /// </summary>
        internal static string ClienteEscapeText {
            get {
                return ResourceManager.GetString("ClienteEscapeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string ClienteEscapeTitle {
            get {
                return ResourceManager.GetString("ClienteEscapeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il cliente è stato fatto uscire..
        /// </summary>
        internal static string ClienteExitText {
            get {
                return ResourceManager.GetString("ClienteExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente uscito.
        /// </summary>
        internal static string ClienteExitTitle {
            get {
                return ResourceManager.GetString("ClienteExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non ho trovato nessun cliente con il codice specificato.
        /// </summary>
        internal static string ClienteNotFoundText {
            get {
                return ResourceManager.GetString("ClienteNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string ClienteNotFoundTitle {
            get {
                return ResourceManager.GetString("ClienteNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi veramente eliminare {0} clienti dalla lista?.
        /// </summary>
        internal static string ClienteRemoveText {
            get {
                return ResourceManager.GetString("ClienteRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string ClienteRemoveTitle {
            get {
                return ResourceManager.GetString("ClienteRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizzato....
        /// </summary>
        internal static string CustomDiscountButton {
            get {
                return ResourceManager.GetString("CustomDiscountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizzato.
        /// </summary>
        internal static string CustomDiscountName {
            get {
                return ResourceManager.GetString("CustomDiscountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stai per togliere tutti i biglietti scontati.
        ///Sei sicuro?.
        /// </summary>
        internal static string DeleteScontoText {
            get {
                return ResourceManager.GetString("DeleteScontoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string DeleteScontoTitle {
            get {
                return ResourceManager.GetString("DeleteScontoTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon IndianaPark {
            get {
                object obj = ResourceManager.GetObject("IndianaPark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricament dei clienti dal database.
        /// </summary>
        internal static string ModelNotLoadedText {
            get {
                return ResourceManager.GetString("ModelNotLoadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore database.
        /// </summary>
        internal static string ModelNotLoadedTitle {
            get {
                return ResourceManager.GetString("ModelNotLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il salvataggio dei clienti sul database.
        /// </summary>
        internal static string ModelNotSavedText {
            get {
                return ResourceManager.GetString("ModelNotSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore Database.
        /// </summary>
        internal static string ModelNotSavedTitle {
            get {
                return ResourceManager.GetString("ModelNotSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun briefing in
        ///orario per &apos;{0}&apos;.
        /// </summary>
        internal static string NoBriefingAvailable {
            get {
                return ResourceManager.GetString("NoBriefingAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non ai aggiunto nessun cliente. Non posso creare biglietti per zero clienti!.
        /// </summary>
        internal static string NoClienteAddedText {
            get {
                return ResourceManager.GetString("NoClienteAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun cliente aggiunto.
        /// </summary>
        internal static string NoClienteAddedTitle {
            get {
                return ResourceManager.GetString("NoClienteAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutti i clienti del nominativo &quot;{0}&quot; sono usciti.
        /// </summary>
        internal static string NominativoEsauritoText {
            get {
                return ResourceManager.GetString("NominativoEsauritoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominativo esaurito.
        /// </summary>
        internal static string NominativoEsauritoTitle {
            get {
                return ResourceManager.GetString("NominativoEsauritoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sono gia stati inseriti altri clienti sotto questo nominativo.
        ///Vuoi aggiungerne degli altri?.
        /// </summary>
        internal static string NominativoEsistenteDescription {
            get {
                return ResourceManager.GetString("NominativoEsistenteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominativo Esitente.
        /// </summary>
        internal static string NominativoEsistenteTitle {
            get {
                return ResourceManager.GetString("NominativoEsistenteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrivi il nominativo.
        /// </summary>
        internal static string NominativoInputText {
            get {
                return ResourceManager.GetString("NominativoInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominativo.
        /// </summary>
        internal static string NominativoInputTitle {
            get {
                return ResourceManager.GetString("NominativoInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non ho trovato nessun nominativo con il codice specificato.
        /// </summary>
        internal static string NominativoNotFoundText {
            get {
                return ResourceManager.GetString("NominativoNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string NominativoNotFoundTitle {
            get {
                return ResourceManager.GetString("NominativoNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi inserire un testo per proseguire!.
        /// </summary>
        internal static string NominativoRequired {
            get {
                return ResourceManager.GetString("NominativoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string NominativoRequiredTitle {
            get {
                return ResourceManager.GetString("NominativoRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrivi il nominativo
        ///dell&apos;abbonato.
        /// </summary>
        internal static string NuovoAbbonamentoNominativoText {
            get {
                return ResourceManager.GetString("NuovoAbbonamentoNominativoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo Abbonamento.
        /// </summary>
        internal static string NuovoAbbonamentoNominativoTitle {
            get {
                return ResourceManager.GetString("NuovoAbbonamentoNominativoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo briefing non ha posti sufficienti per le persone che stai aggiungendo.\nAggiungerli comunque?.
        /// </summary>
        internal static string PostiInsufficientiText {
            get {
                return ResourceManager.GetString("PostiInsufficientiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posti rimasti insufficienti.
        /// </summary>
        internal static string PostiInsufficientiTitle {
            get {
                return ResourceManager.GetString("PostiInsufficientiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi veramente stampare {0} biglietti?.
        /// </summary>
        internal static string PrintTicketText {
            get {
                return ResourceManager.GetString("PrintTicketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!.
        /// </summary>
        internal static string PrintTicketTitle {
            get {
                return ResourceManager.GetString("PrintTicketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biglietti &apos;{0}&apos;{1}: {3,0:C} x #{2} biglietti.
        /// </summary>
        internal static string RiassuntoBiglietti {
            get {
                return ResourceManager.GetString("RiassuntoBiglietti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  scontato &apos;{0}&apos;.
        /// </summary>
        internal static string RiassuntoBigliettiSconto {
            get {
                return ResourceManager.GetString("RiassuntoBigliettiSconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefing per &apos;{0}&apos; alle ore: {1}.
        /// </summary>
        internal static string RiassuntoBriefings {
            get {
                return ResourceManager.GetString("RiassuntoBriefings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla lista clienti sono stati applicati automaticamente altri sconti più convenienti di quelli scelti manualmente.
        /// </summary>
        internal static string ScontiPlanChangedText {
            get {
                return ResourceManager.GetString("ScontiPlanChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio sconti.
        /// </summary>
        internal static string ScontiPlanChangedTitle {
            get {
                return ResourceManager.GetString("ScontiPlanChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore dello sconto.
        /// </summary>
        internal static string ScontoValueText {
            get {
                return ResourceManager.GetString("ScontoValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore dello sconto.
        /// </summary>
        internal static string ScontoValueTitle {
            get {
                return ResourceManager.GetString("ScontoValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale {0,-10:C}.
        /// </summary>
        internal static string TipoClientePartialPrice {
            get {
                return ResourceManager.GetString("TipoClientePartialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale biglietti {0}.
        /// </summary>
        internal static string TotaleBigliettiUntilNow {
            get {
                return ResourceManager.GetString("TotaleBigliettiUntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il codice inserito non è nel formato corretto!
        ///Inserirlo nuovamente.
        /// </summary>
        internal static string WrongCodeFormatText {
            get {
                return ResourceManager.GetString("WrongCodeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        internal static string WrongCodeFormatTitle {
            get {
                return ResourceManager.GetString("WrongCodeFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il codice inserito non è nel formato corretto!
        ///Inserirlo nuovamente.
        /// </summary>
        internal static string WrongCodeLengthText {
            get {
                return ResourceManager.GetString("WrongCodeLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        internal static string WrongCodeLengthTitle {
            get {
                return ResourceManager.GetString("WrongCodeLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il valore inserito non è un numero!
        ///\nNon inserire lettere e usa la virgola come separatore per i decimali.
        /// </summary>
        internal static string WrongNumericalTextDescription {
            get {
                return ResourceManager.GetString("WrongNumericalTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore errato.
        /// </summary>
        internal static string WrongNumericalTextTitle {
            get {
                return ResourceManager.GetString("WrongNumericalTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore del numero fuori dall&apos;intervallo consentito.
        /// </summary>
        internal static string WrongNumericInputText {
            get {
                return ResourceManager.GetString("WrongNumericInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero non corretto.
        /// </summary>
        internal static string WrongNumericInputTitle {
            get {
                return ResourceManager.GetString("WrongNumericInputTitle", resourceCulture);
            }
        }
    }
}
