#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndianaPark.PercorsiAvventura.Persistence.SqlServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="indianapark")]
	public partial class ScontiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTableSconti(TableSconti instance);
    partial void UpdateTableSconti(TableSconti instance);
    partial void DeleteTableSconti(TableSconti instance);
    partial void InsertTableTipiSconto(TableTipiSconto instance);
    partial void UpdateTableTipiSconto(TableTipiSconto instance);
    partial void DeleteTableTipiSconto(TableTipiSconto instance);
    #endregion
		
		public ScontiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScontiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScontiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScontiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TableSconti> TableSconti
		{
			get
			{
				return this.GetTable<TableSconti>();
			}
		}
		
		public System.Data.Linq.Table<TableTipiSconto> TableTipiSconto
		{
			get
			{
				return this.GetTable<TableTipiSconto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="model_sconti")]
	public partial class TableSconti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Key;
		
		private bool _IsComitiva;
		
		private bool _IsPersonale;
		
		private string _TipoSconto;
		
		private string _Nome;
		
		private double _Valore;
		
		private string _CtorParameters;
		
		private bool _IsCustom;
		
		private EntityRef<TableTipiSconto> _TableTipiSconto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyChanging(string value);
    partial void OnKeyChanged();
    partial void OnIsComitivaChanging(bool value);
    partial void OnIsComitivaChanged();
    partial void OnIsPersonaleChanging(bool value);
    partial void OnIsPersonaleChanged();
    partial void OnTipoScontoChanging(string value);
    partial void OnTipoScontoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnValoreChanging(double value);
    partial void OnValoreChanged();
    partial void OnCtorParametersChanging(string value);
    partial void OnCtorParametersChanged();
    partial void OnIsCustomChanging(bool value);
    partial void OnIsCustomChanged();
    #endregion
		
		public TableSconti()
		{
			this._TableTipiSconto = default(EntityRef<TableTipiSconto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="model_key", Storage="_Key", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this.OnKeyChanging(value);
					this.SendPropertyChanging();
					this._Key = value;
					this.SendPropertyChanged("Key");
					this.OnKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sconto_comitiva", Storage="_IsComitiva", DbType="Bit NOT NULL")]
		public bool IsComitiva
		{
			get
			{
				return this._IsComitiva;
			}
			set
			{
				if ((this._IsComitiva != value))
				{
					this.OnIsComitivaChanging(value);
					this.SendPropertyChanging();
					this._IsComitiva = value;
					this.SendPropertyChanged("IsComitiva");
					this.OnIsComitivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sconto_personale", Storage="_IsPersonale", DbType="Bit NOT NULL")]
		public bool IsPersonale
		{
			get
			{
				return this._IsPersonale;
			}
			set
			{
				if ((this._IsPersonale != value))
				{
					this.OnIsPersonaleChanging(value);
					this.SendPropertyChanging();
					this._IsPersonale = value;
					this.SendPropertyChanged("IsPersonale");
					this.OnIsPersonaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tipo_sconto", Storage="_TipoSconto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoSconto
		{
			get
			{
				return this._TipoSconto;
			}
			set
			{
				if ((this._TipoSconto != value))
				{
					this.OnTipoScontoChanging(value);
					this.SendPropertyChanging();
					this._TipoSconto = value;
					this.SendPropertyChanged("TipoSconto");
					this.OnTipoScontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome", Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valore", Storage="_Valore", DbType="Real NOT NULL")]
		public double Valore
		{
			get
			{
				return this._Valore;
			}
			set
			{
				if ((this._Valore != value))
				{
					this.OnValoreChanging(value);
					this.SendPropertyChanging();
					this._Valore = value;
					this.SendPropertyChanged("Valore");
					this.OnValoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ctor_parameters", Storage="_CtorParameters", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CtorParameters
		{
			get
			{
				return this._CtorParameters;
			}
			set
			{
				if ((this._CtorParameters != value))
				{
					this.OnCtorParametersChanging(value);
					this.SendPropertyChanging();
					this._CtorParameters = value;
					this.SendPropertyChanged("CtorParameters");
					this.OnCtorParametersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="custom", Storage="_IsCustom", DbType="Bit NOT NULL")]
		public bool IsCustom
		{
			get
			{
				return this._IsCustom;
			}
			set
			{
				if ((this._IsCustom != value))
				{
					this.OnIsCustomChanging(value);
					this.SendPropertyChanging();
					this._IsCustom = value;
					this.SendPropertyChanged("IsCustom");
					this.OnIsCustomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TableTipiSconto_TableSconti", Storage="_TableTipiSconto", ThisKey="TipoSconto", OtherKey="Tipo", IsForeignKey=true)]
		public TableTipiSconto TableTipiSconto
		{
			get
			{
				return this._TableTipiSconto.Entity;
			}
			set
			{
				TableTipiSconto previousValue = this._TableTipiSconto.Entity;
				if (((previousValue != value) 
							|| (this._TableTipiSconto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TableTipiSconto.Entity = null;
						previousValue.TableSconti.Remove(this);
					}
					this._TableTipiSconto.Entity = value;
					if ((value != null))
					{
						value.TableSconti.Add(this);
						this._TipoSconto = value.Tipo;
					}
					else
					{
						this._TipoSconto = default(string);
					}
					this.SendPropertyChanged("TableTipiSconto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="model_tipi_sconto")]
	public partial class TableTipiSconto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Tipo;
		
		private string _FrameworkType;
		
		private EntitySet<TableSconti> _TableSconti;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnFrameworkTypeChanging(string value);
    partial void OnFrameworkTypeChanged();
    #endregion
		
		public TableTipiSconto()
		{
			this._TableSconti = new EntitySet<TableSconti>(new Action<TableSconti>(this.attach_TableSconti), new Action<TableSconti>(this.detach_TableSconti));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tipo", Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="framework_type", Storage="_FrameworkType", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string FrameworkType
		{
			get
			{
				return this._FrameworkType;
			}
			set
			{
				if ((this._FrameworkType != value))
				{
					this.OnFrameworkTypeChanging(value);
					this.SendPropertyChanging();
					this._FrameworkType = value;
					this.SendPropertyChanged("FrameworkType");
					this.OnFrameworkTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TableTipiSconto_TableSconti", Storage="_TableSconti", ThisKey="Tipo", OtherKey="TipoSconto")]
		public EntitySet<TableSconti> TableSconti
		{
			get
			{
				return this._TableSconti;
			}
			set
			{
				this._TableSconti.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TableSconti(TableSconti entity)
		{
			this.SendPropertyChanging();
			entity.TableTipiSconto = this;
		}
		
		private void detach_TableSconti(TableSconti entity)
		{
			this.SendPropertyChanging();
			entity.TableTipiSconto = null;
		}
	}
}
#pragma warning restore 1591
