<?xml version="1.0" encoding="utf-8"?><Database Name="indianapark_dev" EntityNamespace="IndianaPark.Plugin.Persistence" ContextNamespace="IndianaPark.Plugin.Persistence" Class="PluginParametersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="plugin_parameters" Member="TablePluginParameters">
    <Type Name="TablePluginParameters">
      <Column Name="param_name" Member="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="owner" Member="Owner" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="param_value" Member="Value" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="param_type" Member="Type" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="is_public" Member="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_readonly" Member="IsReadonly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="description" Member="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>